openapi: "3.0.3"
info:
  title: "API documenation"
  description: "writing specs for API documentation"
  version: 1.0.1
servers:
  - url: http://127.0.0.1:8000/consumer
  - url: http://192.168.1.23:3000/consumers

paths:

  /login:
    post:
      summary: "consumer Login"
      description: "Endpoint to authenticate consumer" 
      tags: 
        - login
      requestBody:
        required: true 
        description: "Login credentials"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
              
      responses:
        200:
          description: "Successful login"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        400:
          description: "Invalid input"
        401:
          description: "Unauthorized"


  /all:
    get:
      summary: "Get all products"
      responses:
        '200':
          description: "A list of products"
          
  /register:
    post:
      tags:
      - "Register"
      summary: "Register a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
      responses:
        '201':
          description: "consumer created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
          
  /register/{verify_type}/token/{token_type}:
    patch:
      tags:
      - "Register"
      summary: "verify details"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"

      
        - in: "path"
          name: "token_type"
          required: true
          schema:
            type: "string"
            enum:
              - "resend"
              - "verify"

            
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/verify'
              
      responses:
        '200':
          description: "Verifies Email "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResponse'
          
  /profile:
    get:
      tags:
      - "Profile"
      description: "Personal profile of Citizen "
      summary: "Personal Profile of Citizen "
      
      security:
        - bearerAuth: []  
      
            
      responses:
        '200':
          description: "Shows Personal profile "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalProfileResponse'

  /profile/update:
    patch:
      tags:
      - "Profile"
      summary: "Update a consumer by cofferid"
      
      security:
        - bearerAuth: []  
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/profile'
      responses:
        '200':
          description: "Product updated successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
          
  /profile/{verify_type}:
    patch:
      tags:
      - "Profile"
      summary: "verify details"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"
      
      security:
        - bearerAuth: []  
           
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                token:
                  type: "string"
                  example: "e7a361c8c98d6637"
              
              
      responses:
        '200':
          description: "Verifies Email "
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/VerifyResponse'
                
  /forgot/{verify_type}:
    patch:
      tags:
      - "Forgot Password"
      summary: "verify details"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"
              
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: "string"
                  format: "email"
                  example: "johndoe@example.com"
                mobile:
                  type: "string"
                  example: "1234567890"
                  
      responses:
        '200':
          description: "token sent"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordResponse'
                
  /forgot/{verify_type}/token/{token_type}:
    patch:
      tags:
      - "Forgot Password"
      summary: "verify otp and password change"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"

      
        - in: "path"
          name: "token_type"
          required: true
          schema:
            type: "string"
            enum:
              - "resend"
              - "verify"

            
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
              
      responses:
        '200':
          description: "Verifies Email "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordSuccessResponse'
    
  /reminders/add:
    post:
      tags:
        - reminder
      summary: Add a new reminder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Don't forget to buy milk!"
                target:
                  type: string
                  example: "2024-06-19T15:30:00Z"
      responses:
        201:
          description: Reminder created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
        400:
          description: Bad request
  /reminders:
    get:
      tags:
        - reminder
      summary: Get all reminders
      responses:
        200:
          description: A list of reminders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "60f1a4f8b8d1a0001d71b1e2"
                    message:
                      type: string
                      example: "Don't forget to buy milk!"
                    target:
                      type: string
                      example: "2024-06-19T15:30:00Z"
        500:
          description: Internal server error
          
  /reminders/{remid}/delete:
    delete:
      tags:
        - reminder
      summary: Delete a reminder
      parameters:
        - name: remid
          in: path
          required: true
          schema:
            type: string
            example: "60f1a4f8b8d1a0001d71b1e2"
      responses:
        200:
          description: Reminder deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReminderResponse'
        404:
          description: Reminder not found
        500:
          description: Internal server error
      
      
          
          



components:
  schemas:
    
    login:
      type: "object"
      properties: 
          action:
            type: "string"
            description: "Type of action" 
            example: 'login'
          logintype:
            type: "string"
            description: "Type of login" 
            example: 'email'
          email:
            type: "string"
            format: "email"
            description: "User's email address" 
            example: 'vijay123@gmail.com'
          password:
            type: "string"
            format: "password"
            description: "User's password" 
            example: 'dev123'

    LoginResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          description: "Indicates whether an error occurred"
        message:
          type: "string"
          description: "Message indicating the result of the login attempt"
        token:
          type: "string"
          description: "JWT Token"
        data:
          type: "object"
          properties:
            coffer_id:
              type: "string"
              description: "Coffer ID of the user"
            custom_uid:
              type: "string"
              description: "Custom user ID"
            first_name:
              type: "string"
              description: "User's first name"
            last_name:
              type: "string"
              description: "User's last name"
            email_verified:
              type: "boolean"
              description: "Indicates if the user's email is verified"
            mobile_verified:
              type: "boolean"
              description: "Indicates if the user's mobile number is verified"
            lastlogin:
              type: "string"
              format: "date-time"
              description: "Timestamp of the user's last login"
            email:
              type: "string"
              format: "email"
              description: "User's email address"
            mobile:
              type: "string"
              description: "User's mobile number"
            pk:
              type: "string"
              description: "Primary key of the user"
    profile:
      type: "object"
      properties:
        first_name:
          type: "string"
          example: "John"
        middle_name:
          type: "string"
          example: "fricks"
        last_name:
          type: "string"
          example: "Doe"
        email:
          type: "string"
          format: "email"
          example: "johndoe@example.com"
        mobile:
          type: "string"
          example: "1234567890"
        old_password:
          type: "string"
          format: "password"
          example: "password123"
        new_password:
          type: "string"
          format: "password"
          example: "password123"
        confirm_password:
          type: "string"
          format: "password"
          example: "password123"
          
    register:
      type: "object"
      properties:
        first_name:
          type: "string"
          example: "John"
        last_name:
          type: "string"
          example: "Doe"
        country:
          type: "string"
          example: "USA"
        email:
          type: "string"
          format: "email"
          example: "johndoe@example.com"
        mobile:
          type: "string"
          example: "1234567890"
        password:
          type: "string"
          format: "password"
          example: "password123"
        confirm_password:
          type: "string"
          format: "password"
          example: "password123"
      required:
        - "first_name"
        - "last_name"
        - "country"
        - "password"
        - "confirm_password"
      
    
    verify:
      type: "object"
      properties:
        email:
          type: "string"
          example: "abc@gmail.com"
        mobile:
          type: "string"
          example: 1234567890
        token:
          type: "string"
          example: "e7a361c8c98d6637"
          
    VerifyResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg1:
          type: "string"
          example: "Email verification successful."
        msg:
          type: "string"
          example: "mobile verification successful."
          
    PersonalProfileResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false    
        data:
          type: "object"
          properties:
            first_name:
              type: "string"
              example: "Vengadesh"
            last_name:
              type: "string"
              example: "R" 
            middle_name:
              type: "string"
              example: "Waran"
            dob:
              type: "string"
              example: "19-01-1977"
            email:
              type: "string"
              example: "abc@gmail.com"
            mobile:
              type: "string"
              example: 1664633453
            citizen:
              type: array
              items:
                type: "object"
                properties:
                  country:
                    type: "string"
                    example: "India"
                  affiliation_type:
                    type: "string"
                    example: citz
                  mobile_phone:
                    type: "string"
                    example: ""    
                  home_address:
                    type: "string"
                    example: "Thanjavur"
                  alt_phone:
                    type: "string"
                    example: ""
                  index:
                    type: "string"
                    example: "citizen_primary"  
                  work_phone:
                    type: "string"
                    example: ""
                  work_address:
                    type: "string"
                    example: "Karanataka,Bangalore " 
                    
    ResetPasswordResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "A token to reset your password is sent to your mobile. It is valid for 5 mins"
        coffer_id:
          type: "string"
          example: "939d55f9ef8908ba"
          
    ResetPasswordRequest:
      type: "object"
      properties:
        coffer_id:
          type: "string"
          example: "939d55f9ef8908ba"
        otp:
          type: "string"
          example: "773922"
        password:
          type: "string"
          example: "000000"
        confirm_password:
          type: "string"
          example: "000000"
      required:
        - "coffer_id"
        - "otp"
        - "password"
        - "confirm_password"
        
    ResetPasswordSuccessResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "Password reset successful. Please login to access your Coffer."
          
    UpdateResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "profile details updated successfully"
          
    RegisterResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "consumer creted successfully"
          
    Reminder:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "reminder created successfully"
          
    ReminderResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "reminder deleted successfully"
          
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: "http"
        scheme: "bearer"
        bearerFormat: "JWT"
        

    

      