openapi: "3.0.3"
info:
  title: "API documenation"
  description: "writing specs for API documentation"
  version: 1.0.1
servers:
  - url: http://127.0.0.1:8000/consumer

paths:
    
  /all:
    get:
      summary: "Get all products"
      responses:
        '200':
          description: "A list of products"
          
  /register:
    post:
      tags:
      - "Register"
      summary: "Register a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
      responses:
        '201':
          description: "consumer created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
          
  /register/{verify_type}/token/{token_type}:
    patch:
      tags:
      - "Register"
      summary: "verify details"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"

      
        - in: "path"
          name: "token_type"
          required: true
          schema:
            type: "string"
            enum:
              - "resend"
              - "verify"

            
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/verify'
              
      responses:
        '200':
          description: "Verifies Email "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResponse'
          
  /{cofferid}:
    get:
      tags:
      - "Profile"
      description: "Personal profile of Citizen "
      summary: "Personal Profile of Citizen "
      parameters:
        - in: "path"
          name: "cofferid"
          required: true
          schema:
            type: "string"
            example: "939d55f9ef8908ba"
            
      responses:
        '200':
          description: "Shows Personal profile "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalProfileResponse'

  /{cofferid}/profile/update:
    patch:
      tags:
      - "Profile"
      summary: "Update a consumer by cofferid"
      parameters:
        - in: "path"
          name: "cofferid"
          required: true
          schema:
            type: "string"
            example: "939d55f9ef8908ba"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/profile'
      responses:
        '200':
          description: "Product updated successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
          
  /{cofferid}/profile/{verify_type}:
    patch:
      tags:
      - "Profile"
      summary: "verify details"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"
           
        
        - in: "path"
          name: "cofferid"
          required: true
          schema:
            type: "string"
            example: "939d55f9ef8908ba"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                token:
                  type: "string"
                  example: "e7a361c8c98d6637"
              
              
      responses:
        '200':
          description: "Verifies Email "
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/VerifyResponse'
                
  /forgot/{verify_type}:
    patch:
      tags:
      - "Forgot Password"
      summary: "verify details"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"
              
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: "string"
                  format: "email"
                  example: "johndoe@example.com"
                mobile:
                  type: "string"
                  example: "1234567890"
                  
      responses:
        '200':
          description: "token sent"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordResponse'
                
  /forgot/{verify_type}/token/{token_type}:
    patch:
      tags:
      - "Forgot Password"
      summary: "verify otp and password change"
      parameters:
        - in: "path"
          name: "verify_type"
          required: true
          schema:
            type: "string"
            enum:
              - "email"
              - "mobile"

      
        - in: "path"
          name: "token_type"
          required: true
          schema:
            type: "string"
            enum:
              - "resend"
              - "verify"

            
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
              
      responses:
        '200':
          description: "Verifies Email "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordSuccessResponse'
    
              
      
      
          
          



components:
  schemas:
    citizenship:
      type: "object"
      properties:
        index:
          type: "string"
          example: "12345"
        country:
          type: "string"
          example: "USA"
        affiliation_type:
          type: "string"
          example: "Employee"
        work_address:
          type: "string"
          example: "123 Work St, Worktown, WT 54321"
        home_address:
          type: "string"
          example: "456 Home St, Hometown, HT 67890"
        mobile_phone:
          type: "string"
          example: "1234567890"
        work_phone:
          type: "string"
          example: "0987654321"
        alt_phone:
          type: "string"
          example: "1122334455"
        affiliation_countryid:
          type: "string"
          example: "US"
      required:
        - "country"
        - "affiliation_type"
        - "mobile_phone"
        - "home_address"
        
        
    profile:
      type: "object"
      properties:
        first_name:
          type: "string"
          example: "John"
        middle_name:
          type: "string"
          example: "fricks"
        last_name:
          type: "string"
          example: "Doe"
        email:
          type: "string"
          format: "email"
          example: "johndoe@example.com"
        mobile:
          type: "string"
          example: "1234567890"
        old_password:
          type: "string"
          format: "password"
          example: "password123"
        new_password:
          type: "string"
          format: "password"
          example: "password123"
        confirm_password:
          type: "string"
          format: "password"
          example: "password123"
          
    register:
      type: "object"
      properties:
        first_name:
          type: "string"
          example: "John"
        last_name:
          type: "string"
          example: "Doe"
        country:
          type: "string"
          example: "USA"
        email:
          type: "string"
          format: "email"
          example: "johndoe@example.com"
        mobile:
          type: "string"
          example: "1234567890"
        password:
          type: "string"
          format: "password"
          example: "password123"
        confirm_password:
          type: "string"
          format: "password"
          example: "password123"
      required:
        - "first_name"
        - "last_name"
        - "country"
        - "password"
        - "confirm_password"
      
    
    verify:
      type: "object"
      properties:
        email:
          type: "string"
          example: "abc@gmail.com"
        mobile:
          type: "string"
          example: 1234567890
        token:
          type: "string"
          example: "e7a361c8c98d6637"
          
    VerifyResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg1:
          type: "string"
          example: "Email verification successful."
        msg:
          type: "string"
          example: "mobile verification successful."
          
    PersonalProfileResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false    
        data:
          type: "object"
          properties:
            first_name:
              type: "string"
              example: "Vengadesh"
            last_name:
              type: "string"
              example: "R" 
            middle_name:
              type: "string"
              example: "Waran"
            dob:
              type: "string"
              example: "19-01-1977"
            email:
              type: "string"
              example: "abc@gmail.com"
            mobile:
              type: "string"
              example: 1664633453
            citizen:
              type: array
              items:
                type: "object"
                properties:
                  country:
                    type: "string"
                    example: "India"
                  affiliation_type:
                    type: "string"
                    example: citz
                  mobile_phone:
                    type: "string"
                    example: ""    
                  home_address:
                    type: "string"
                    example: "Thanjavur"
                  alt_phone:
                    type: "string"
                    example: ""
                  index:
                    type: "string"
                    example: "citizen_primary"  
                  work_phone:
                    type: "string"
                    example: ""
                  work_address:
                    type: "string"
                    example: "Karanataka,Bangalore " 
                    
    ResetPasswordResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "A token to reset your password is sent to your mobile. It is valid for 5 mins"
        coffer_id:
          type: "string"
          example: "939d55f9ef8908ba"
          
    ResetPasswordRequest:
      type: "object"
      properties:
        coffer_id:
          type: "string"
          example: "939d55f9ef8908ba"
        otp:
          type: "string"
          example: "773922"
        password:
          type: "string"
          example: "000000"
        confirm_password:
          type: "string"
          example: "000000"
      required:
        - "coffer_id"
        - "otp"
        - "password"
        - "confirm_password"
        
    ResetPasswordSuccessResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "Password reset successful. Please login to access your Coffer."
          
    UpdateResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "profile details updated successfully"
          
    RegisterResponse:
      type: "object"
      properties:
        error:
          type: "boolean"
          example: false
        msg:
          type: "string"
          example: "consumer creted successfully"
          
    

      